name: crystal-gchat-server
version: "1.0.3"
summary: Crystal Lang GlobalChat2 Server
description: Custom encrypted chat with live drawing

grade: stable
confinement: strict
base: core18

apps:
  crystal-gchat-server:
    command: bin/crystal-gchat-server
  change-passwords:
    command: bin/change-passwords

parts:
  source: ./
  crystal-gchat-server:
    plugin: crystal
